### ISSUE TITLE
 legacy "View Engine" libraries

### ISSUE THREAD

**Issue by wilson3q** [vugar005/ngx-router-animations#10]
Hello,

Currently I am using ngx-router-animations in one of my angular app. When I build it using latest Angular 13, I saw below warnings:

```
Processing legacy "View Engine" libraries:
...
- ngx-router-animations [es2015/esm2015] (https://github.com/vugar005/ngx-router-animations)
...
Encourage the library authors to publish an Ivy distribution.
```

Can you please help to upgrade this library to Ivy?
Refer to [this guide](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/url)

Thanks.

**Comment by vugar005** [comment]
Hi @wilson3q, sorry for late reply.
Now package is upgraded to v13 which supports ivy compilation mode.
Thanks!

**Comment by wilson3q** [comment]
thanks!
