### ISSUE TITLE
Typographic Errors

### ISSUE THREAD

**Issue by mrellipse** [vugar005/ngx-router-animations#2]
The word [tansition](https://github.com/vugar005/ngx-router-animations/search?q=Tansitions&unscoped_q=Tansitions) appears instead of 'transition'

**Comment by DanielsJR** [comment]
in rotateCubeToBottom there's a doble parentheses
 style({ transform: 'translateY(-50%) translateZ(-200px) rotateX(45deg))', offset: 0.5 }),

**Comment by vugar005** [comment]
@mrellipse  @DanielsJR  thank you for report. I am gonna fix them on next release.
